from .artist import Artist
from .cm import ScalarMappable

class Collection(Artist, ScalarMappable): ...
class _CollectionWithSizes(Collection): ...
class PolyCollection(_CollectionWithSizes): ...
class PathCollection(_CollectionWithSizes): ...
