from typing import Optional

from .artist import Artist

class Text(Artist):
    def get_text(self) -> str: ...
    def set_color(self, color: str) -> None: ...
    def set_text(self, s: Optional[str]) -> None: ...
