"""
This type stub file was generated by pyright.
"""

import _plotly_utils.basevalidators

class XhoverformatValidator(_plotly_utils.basevalidators.StringValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


