"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._hoverlabel import Hoverlabel
from ._legendgrouptitle import Legendgrouptitle
from ._marker import Marker
from ._stream import Stream
from . import hoverlabel, legendgrouptitle, marker

if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
