FROM node:18

SHELL ["/bin/bash", "-c"]

# Install build-essential, curl, python and python3-pip
RUN echo 'Installing build-essential, curl, python and python3-pip...' && apt-get update && \
  apt-get install -y \
  build-essential \
  curl \
  python-is-python3 \
  python3-pip

# Install rustup
RUN echo 'Installing rustup...' && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install wasm-pack
RUN echo 'Installing wasm-pack...' && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

# Install wasm32-unknown-unknown target
RUN echo 'Installing wasm32-unknown-unknown target...' && rustup target add wasm32-unknown-unknown

# Install cargo-watch
RUN echo 'Installing cargo-watch...' && cargo install cargo-watch

WORKDIR /quadratic

CMD ["bash", "-c", "source ~/.bashrc && npm install --no-audit --no-fund && npm run compile --workspace=quadratic-shared && npm run dev:docker"]