"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._box import Box
from ._hoverlabel import Hoverlabel
from ._legendgrouptitle import Legendgrouptitle
from ._line import Line
from ._marker import Marker
from ._meanline import Meanline
from ._selected import Selected
from ._stream import Stream
from ._unselected import Unselected
from . import box, hoverlabel, legendgrouptitle, marker, selected, unselected

if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
