// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellBorderStyle } from "./CellBorderStyle";

export interface CellBorder { color?: string, type?: CellBorderStyle, }