"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._center import Center
from ._domain import Domain
from ._lataxis import Lataxis
from ._lonaxis import Lonaxis
from ._projection import Projection
from . import projection

if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
