name: Tests E2E
description: "E2E tests"
inputs:
  e2e_url:
    description: "Base url of deployment"
    required: true
  shard_index:
    description: "Index of the shard to run"
    required: true
  shard_total:
    description: "Total number of shards"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: |
          test/e2e
        sparse-checkout-cone-mode: false
        fetch-tags: false
        submodules: false
        lfs: false

    - name: Setup Node
      uses: useblacksmith/setup-node@v5
      with:
        node-version: 24

    - name: Install AWS CLI
      run: |
        apt-get update
        apt-get install -y awscli
      shell: bash

    - name: Install Dependencies
      run: cd test/e2e && npm install
      shell: bash

    - name: Get WorkOS credentials from SSM
      id: get-workos-creds
      run: |
        WORKOS_CLIENT_ID=$(aws ssm get-parameter --name "/quadratic-development/WORKOS_CLIENT_ID" --with-decryption --query "Parameter.Value" --output text)
        WORKOS_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/WORKOS_API_KEY" --with-decryption --query "Parameter.Value" --output text)
        echo "::add-mask::$WORKOS_CLIENT_ID"
        echo "::add-mask::$WORKOS_API_KEY"
        echo "workos_client_id=$WORKOS_CLIENT_ID" >> $GITHUB_OUTPUT
        echo "workos_api_key=$WORKOS_API_KEY" >> $GITHUB_OUTPUT
      shell: bash

    - name: Run Playwright tests
      run: cd test/e2e && npm run test -- --shard ${{ inputs.shard_index }}/${{ inputs.shard_total }}
      shell: bash
      env:
        CI: true
        GITHUB_ACTIONS: false
        E2E_URL: ${{ inputs.e2e_url }}
        WORKOS_CLIENT_ID: ${{ steps.get-workos-creds.outputs.workos_client_id }}
        WORKOS_API_KEY: ${{ steps.get-workos-creds.outputs.workos_api_key }}

    - name: Upload blob report to GitHub Actions Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      id: upload-playwright-report
      with:
        name: blob-report-${{ github.run_id }}-${{ inputs.shard_index }}
        path: test/e2e/blob-report
        retention-days: 1
        overwrite: true
        include-hidden-files: true
        if-no-files-found: warn
