name: Tests E2E
description: "E2E tests"
inputs:
  e2e_url:
    description: "Base url of deployment"
    required: true
  shard_index:
    description: "Index of the shard to run"
    required: true
  shard_total:
    description: "Total number of shards"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: |
          test/e2e
        sparse-checkout-cone-mode: false
        fetch-tags: false
        submodules: false
        lfs: false

    - name: Setup Node
      uses: useblacksmith/setup-node@v5
      with:
        node-version: 24

    - name: Install Dependencies
      run: cd test/e2e && npm install
      shell: bash

    - name: Run Playwright tests
      id: run-tests
      continue-on-error: true
      run: export E2E_URL=${{ inputs.e2e_url }} && cd test/e2e && npm run test -- --shard ${{ inputs.shard_index }}/${{ inputs.shard_total }}
      shell: bash
      env:
        CI: true
        GITHUB_ACTIONS: false

    - name: Upload blob report to GitHub Actions Artifacts
      uses: actions/upload-artifact@v4
      if: always() && !cancelled()
      continue-on-error: true
      id: upload-playwright-report
      with:
        name: blob-report-${{ github.run_id }}-${{ inputs.shard_index }}
        path: test/e2e/blob-report
        retention-days: 1
        overwrite: true
        include-hidden-files: true
        if-no-files-found: warn

    - name: Fail if tests failed
      if: steps.run-tests.outcome == 'failure'
      run: exit 1
      shell: bash
