"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Tuple

async def getCell(p_x: int, p_y: int, sheet: str = ...) -> int | float | str | bool | None:
    """
    Reference a single cell in the grid.
    """
    ...

async def cell(p_x: int, p_y: int, sheet: str = ...) -> int | float | str | bool | None:
    """
    Reference a single cell in the grid.
    """
    ...

async def c(p_x: int, p_y: int, sheet: str = ...) -> int | float | str | bool | None:
    """
    Reference a single cell in the grid.
    """
    ...

async def getCells(p0: Tuple[int, int], p1: Tuple[int, int], sheet: str = ..., first_row_header: bool = ...) -> pd.DataFrame:
    """
    Reference multiple cells in the grid.
    """
    ...

async def cells(p0: Tuple[int, int], p1: Tuple[int, int], sheet: str = ..., first_row_header: bool = ...) -> pd.DataFrame:
    """
    Reference multiple cells in the grid.
    """
    ...

