"""
This type stub file was generated by pyright.
"""

import sys
import ipywidgets as _ipywidgets
from typing import TYPE_CHECKING
from ..graph_objs import AngularAxis, Annotation, Annotations, Bar, Barpolar, Box, Candlestick, Carpet, Choropleth, Choroplethmapbox, ColorBar, Cone, Contour, Contourcarpet, Contours, Data, Densitymapbox, ErrorX, ErrorY, ErrorZ, Figure, Font, Frame, Frames, Funnel, Funnelarea, Heatmap, Heatmapgl, Histogram, Histogram2d, Histogram2dContour, Histogram2dcontour, Icicle, Image, Indicator, Isosurface, Layout, Legend, Line, Margin, Marker, Mesh3d, Ohlc, Parcats, Parcoords, Pie, Pointcloud, RadialAxis, Sankey, Scatter, Scatter3d, Scattercarpet, Scattergeo, Scattergl, Scattermapbox, Scatterpolar, Scatterpolargl, Scattersmith, Scatterternary, Scene, Splom, Stream, Streamtube, Sunburst, Surface, Table, Trace, Treemap, Violin, Volume, Waterfall, XAxis, XBins, YAxis, YBins, ZAxis, bar, barpolar, box, candlestick, carpet, choropleth, choroplethmapbox, cone, contour, contourcarpet, densitymapbox, funnel, funnelarea, heatmap, heatmapgl, histogram, histogram2d, histogram2dcontour, icicle, image, indicator, isosurface, layout, mesh3d, ohlc, parcats, parcoords, pie, pointcloud, sankey, scatter, scatter3d, scattercarpet, scattergeo, scattergl, scattermapbox, scatterpolar, scatterpolargl, scattersmith, scatterternary, splom, streamtube, sunburst, surface, table, treemap, violin, volume, waterfall
from packaging.version import Version as _Version

if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
