"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._circle import Circle
from ._fill import Fill
from ._line import Line
from ._symbol import Symbol
from . import symbol

if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
