"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._labelfont import Labelfont

if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
