"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._dimension import Dimension
from ._domain import Domain
from ._labelfont import Labelfont
from ._legendgrouptitle import Legendgrouptitle
from ._line import Line
from ._rangefont import Rangefont
from ._stream import Stream
from ._tickfont import Tickfont
from ._unselected import Unselected
from . import legendgrouptitle, line, unselected

if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
