AWSTemplateFormatVersion: 2010-09-09
Description: Quadratic Preview - Docker Deployment Template

Parameters:
  SubDomainName:
    Type: String
    Description: Subdomain name, used as https://<subdomain>.quadratic-preview.com
  ImageTag:
    Type: String
    Description: Image tag to use for all services

Resources:
  # Security Group for the EC2 instance
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Tags:
        - Key: Name
          Value: !Ref ImageTag
      GroupDescription: !Ref ImageTag
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # IAM Role for the EC2 instance
  EC2Role:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Tags:
        - Key: Name
          Value: !Ref ImageTag
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess

  # IAM Instance Profile for the EC2 instance
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Roles:
        - !Ref EC2Role

  # EC2 instance
  EC2Instance:
    Type: AWS::EC2::Instance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ImageTag}"
      InstanceType: m7a.large
      ImageId: ami-075686beab831bb7f # AMI for us-west-2 (Ubuntu 24.04 LTS amd64)
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
        - !Ref SecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # Update and install dependencies
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common unzip jq

          # Install AWS CLI v2
          sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip awscliv2.zip
          sudo ./aws/install
          sudo rm -rf aws awscliv2.zip

          # Install Docker
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo chown ubuntu /var/run/docker.sock
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu

          # Download Quadratic initialization script
          sudo curl -sSf https://raw.githubusercontent.com/quadratichq/quadratic-selfhost/main/init-aws-preview.sh -o init.sh

          # Fetch License Key
          LICENSE_KEY="$(aws ssm get-parameter --name "/quadratic-development/QUADRATIC_LICENSE_KEY" --with-decryption --query "Parameter.Value" --output text)"

          # Generate Domain Name
          DOMAIN_NAME="${SubDomainName}.quadratic-preview.com"

          # Run Quadratic initialization script
          sudo chmod +x init.sh
          sudo ./init.sh $LICENSE_KEY $DOMAIN_NAME

          # Append environment variables to .env file
          cat << EOF >> /quadratic-selfhost/.env
          AWS_S3_REGION=$(aws ssm get-parameter --name "/quadratic-development/AWS_S3_REGION" --with-decryption --query "Parameter.Value" --output text)
          AWS_S3_ACCESS_KEY_ID=$(aws ssm get-parameter --name "/quadratic-development/AWS_S3_ACCESS_KEY_ID" --with-decryption --query "Parameter.Value" --output text)
          AWS_S3_SECRET_ACCESS_KEY=$(aws ssm get-parameter --name "/quadratic-development/AWS_S3_SECRET_ACCESS_KEY" --with-decryption --query "Parameter.Value" --output text)

          # auth
          AUTH_TYPE=$(aws ssm get-parameter --name "/quadratic-development/AUTH_TYPE" --with-decryption --query "Parameter.Value" --output text)
          WORKOS_CLIENT_ID=$(aws ssm get-parameter --name "/quadratic-development/WORKOS_CLIENT_ID" --with-decryption --query "Parameter.Value" --output text)
          WORKOS_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/WORKOS_API_KEY" --with-decryption --query "Parameter.Value" --output text)
          JWKS_URI=$(aws ssm get-parameter --name "/quadratic-development/JWKS_URI" --with-decryption --query "Parameter.Value" --output text)

          # gcp
          GCP_REGION=$(aws ssm get-parameter --name "/quadratic-development/GCP_REGION" --with-decryption --query "Parameter.Value" --output text)
          GCP_REGION_ANTHROPIC=$(aws ssm get-parameter --name "/quadratic-development/GCP_REGION_ANTHROPIC" --with-decryption --query "Parameter.Value" --output text)
          GCP_PROJECT_ID=$(aws ssm get-parameter --name "/quadratic-development/GCP_PROJECT_ID" --with-decryption --query "Parameter.Value" --output text)
          GCP_CLIENT_EMAIL=$(aws ssm get-parameter --name "/quadratic-development/GCP_CLIENT_EMAIL" --with-decryption --query "Parameter.Value" --output text)
          GCP_PRIVATE_KEY=$(aws ssm get-parameter --name "/quadratic-development/GCP_PRIVATE_KEY" --with-decryption --query "Parameter.Value" --output text)
          GCP_GEMINI_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/GCP_GEMINI_API_KEY" --with-decryption --query "Parameter.Value" --output text)

          # ai api keys
          BILLING_AI_USAGE_LIMIT=$(aws ssm get-parameter --name "/quadratic-development/BILLING_AI_USAGE_LIMIT" --with-decryption --query "Parameter.Value" --output text)
          ANTHROPIC_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/ANTHROPIC_API_KEY" --with-decryption --query "Parameter.Value" --output text)
          OPENAI_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/OPENAI_API_KEY" --with-decryption --query "Parameter.Value" --output text)
          AZURE_OPENAI_ENDPOINT=$(aws ssm get-parameter --name "/quadratic-development/AZURE_OPENAI_ENDPOINT" --with-decryption --query "Parameter.Value" --output text)
          AZURE_OPENAI_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/AZURE_OPENAI_API_KEY" --with-decryption --query "Parameter.Value" --output text)
          XAI_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/XAI_API_KEY" --with-decryption --query "Parameter.Value" --output text)
          BASETEN_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/BASETEN_API_KEY" --with-decryption --query "Parameter.Value" --output text)
          FIREWORKS_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/FIREWORKS_API_KEY" --with-decryption --query "Parameter.Value" --output text)
          OPEN_ROUTER_API_KEY=$(aws ssm get-parameter --name "/quadratic-development/OPEN_ROUTER_API_KEY" --with-decryption --query "Parameter.Value" --output text)
          AI_ALLOWANCE_PRO=$(aws ssm get-parameter --name "/quadratic-development/AI_ALLOWANCE_PRO" --with-decryption --query "Parameter.Value" --output text)
          AI_ALLOWANCE_BUSINESS=$(aws ssm get-parameter --name "/quadratic-development/AI_ALLOWANCE_BUSINESS" --with-decryption --query "Parameter.Value" --output text)
          AI_MARGIN=$(aws ssm get-parameter --name "/quadratic-development/AI_MARGIN" --with-decryption --query "Parameter.Value" --output text)

          # stripe
          STRIPE_SECRET_KEY=$(aws ssm get-parameter --name "/quadratic-development/STRIPE_SECRET_KEY" --with-decryption --query "Parameter.Value" --output text)

          # plaid
          PLAID_CLIENT_ID=$(aws ssm get-parameter --name "/quadratic-development/PLAID_CLIENT_ID" --with-decryption --query "Parameter.Value" --output text)
          PLAID_SECRET=$(aws ssm get-parameter --name "/quadratic-development/PLAID_SECRET" --with-decryption --query "Parameter.Value" --output text)
          PLAID_ENVIRONMENT=$(aws ssm get-parameter --name "/quadratic-development/PLAID_ENVIRONMENT" --with-decryption --query "Parameter.Value" --output text)

          # misc
          CONNECTION_DEMO=$(aws ssm get-parameter --name "/quadratic-development/CONNECTION_DEMO" --with-decryption --query "Parameter.Value" --output text)

          # aws ecr
          ECR_URL=${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          IMAGE_TAG=${ImageTag}
          EOF

          # Create login.sh script and run it
          cat << 'EOF' > /quadratic-selfhost/login.sh
          #!/bin/bash
          aws ecr get-login-password --region ${AWS::Region} | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          EOF

          sudo chmod +x /quadratic-selfhost/login.sh
          sudo chmod +x /quadratic-selfhost/pull_start.sh

          cd /quadratic-selfhost
          ./login.sh
          ./pull_start.sh

  # Global Accelerator
  GlobalAccelerator:
    Type: AWS::GlobalAccelerator::Accelerator
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub "${ImageTag}"
      Enabled: true
      Tags:
        - Key: Name
          Value: !Ref ImageTag

  # Global Accelerator Listener
  GlobalAcceleratorListener:
    Type: AWS::GlobalAccelerator::Listener
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AcceleratorArn: !Ref GlobalAccelerator
      Protocol: TCP
      PortRanges:
        - FromPort: 80
          ToPort: 80
        - FromPort: 443
          ToPort: 443

  # Global Accelerator Endpoint Group
  GlobalAcceleratorEndpointGroup:
    Type: AWS::GlobalAccelerator::EndpointGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      ListenerArn: !Ref GlobalAcceleratorListener
      EndpointGroupRegion: !Ref AWS::Region
      EndpointConfigurations:
        - EndpointId: !Ref EC2Instance
          Weight: 100
          ClientIPPreservationEnabled: true

  # DNS record for the main application
  DNSRecord:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneId: Z0126430TJ1UYIMO3SYX
      Name: !Sub "${SubDomainName}.quadratic-preview.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt GlobalAccelerator.DnsName
        HostedZoneId: Z2BJ6XQ5FK7U4H
        EvaluateTargetHealth: true

  # Wildcard DNS record for all services on subdomains
  WildcardDNSRecord:
    Type: AWS::Route53::RecordSet
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      HostedZoneId: Z0126430TJ1UYIMO3SYX
      Name: !Sub "*.${SubDomainName}.quadratic-preview.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt GlobalAccelerator.DnsName
        HostedZoneId: Z2BJ6XQ5FK7U4H
        EvaluateTargetHealth: true

Outputs:
  WebsiteURL:
    Description: Website URL
    Value: !Sub "https://${SubDomainName}.quadratic-preview.com"
