apiVersion: v1
kind: Namespace
metadata:
  name: quadratic-cloud
  labels:
    name: quadratic-cloud
    app.kubernetes.io/name: quadratic-cloud
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "Quadratic Cloud"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quadratic-cloud-network-policy
  namespace: quadratic-cloud
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: quadratic-cloud
  egress:
    - {}
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
