from typing import overload

from . import ndarray

def assert_allclose(
    actual: ndarray, desired: ndarray, rtol: float = ..., atol: float = ...
) -> None: ...
def assert_array_equal(actual: ndarray, desired: ndarray) -> None: ...
@overload
def assert_almost_equal(actual: ndarray, desired: ndarray, decimal: float) -> None: ...
@overload
def assert_almost_equal(actual: float, desired: float, decimal: float) -> None: ...
