"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._domain import Domain
from ._hoverlabel import Hoverlabel
from ._insidetextfont import Insidetextfont
from ._leaf import Leaf
from ._legendgrouptitle import Legendgrouptitle
from ._marker import Marker
from ._outsidetextfont import Outsidetextfont
from ._pathbar import Pathbar
from ._root import Root
from ._stream import Stream
from ._textfont import Textfont
from ._tiling import Tiling
from . import hoverlabel, legendgrouptitle, marker, pathbar

if sys.version_info < (3, 7) or TYPE_CHECKING:
    ...
else:
    ...
