name: CI
on: push

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - run: npm install
      - run: npm test
